### ISSUE TITLE
[Parser] Handling empty lines

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/sourir#13]
Parser currently chokes on empty lines.

**Comment by gasche** [comment]
So @o- suggested that we try to keep the parser and pretty-printer synchronized, such that we could hope for perfect print-back of "reasonably formatted" code. Should we have a no-op `Blank` instruction to preserve this property, or turn blank lines into empty comments (and empty comments back into blank lines), or forget about it and go for "printing then parsing returns the same AST" as a weaker but reasonable property?

(I changed the `Comment` payload to drop the first `#`, but I can change it back so that we can actually distinguish blank lines from empty comments `#`.)

**Comment by o-** [comment]
i find an empty line statement too much!
for now our tests assert that: disassemble produces the same output as disassemble -> parse -> disassemble -- nothing more
i think that is enough for now. but if you think its important for users that we can point to the exact initial input I would rather retract my initial position and have a source mapping after all. it can be a simple table:
pc -> line# which we keep with the intructions

**Comment by gasche** [comment]
(See #28 )
