### ISSUE TITLE
Renaming "invalidate" into "guard".

### ISSUE THREAD

**Issue by gasche** [reactorlabs/sourir#40]
I gave a short presentation of speculative optimizations in general and some bits of Sourir IR to someone last week, and I found that using "invalidate" didn't really make sense to a newcomer, so I used "guard" instead. The problem with invalidate is that when reading

    invalidate (x > 0) foo

it is not clear if we invalidate if `(x > 0)` holds, or if it does not. On the other hard,

    guard (x > 0) foo

seems more clear, to me: we guard the fact that `(x > 0)` holds, so this is what the fast-path will assume. Of course, the status of the `foo` label is, conversely, a bit less clear (the "invalidation label" is clear, the "guard label" is not), but I think that this is overall less confusing. Note that we can have several keywords in our instruction, so `guard (x > 0) failwith l` for example would be possible (or `orelse`, `failto`, `or`). Another approach, relying on an extra keyword, would be `invalidate unless (x > 0)` (or `invalidate if (x <= 0)`), but having more negations makes things maybe a bit less clear.

Should we consider actually making the change?

**Comment by o-** [comment]
I agree with invalidate being a bad name, especially with the condition being counter intuitive.

at least in the semantics doc we now changed it to "osr" and flipped the condition. Not sure if that was to your liking.

While I agree that for our current usecase "guard" would be the best I think in general "osr" is nicer. Because we can use it for osr-in and osr-out. Consider e.g.:

    osr (invocation_count > 100) optimized

Instead of the unless keyword I would propose to extend our primop with an unary negation. we would express "invalidate if x" or "guard not x" as "osr x" and "invalidate unless x" or "guard x" as "osr !(x)"

**Comment by gasche** [comment]
I'm ok with `osr` and agree with the plan to use it in the implementation.
