### ISSUE TITLE
Add Functions

### ISSUE THREAD

**Issue by o-** [reactorlabs/sourir#63]
Let's start a discussion about how to add functions.

This is my first shot at it: 
Updated:
https://github.com/reactorlabs/sourir/compare/master...o-:add_functions2

**Comment by gasche** [comment]
I think it would be easier to discuss as a pull request -- you can have "[WIP]" in the title if you are worried we would merge.

I read the initial patch you sent yesterday, and I was about to say the the restricted design of `const a = call ...` was made so that you could keep only a stack of program counters, instead of having to keep full continuations. The new version seems to have changed that, but then maybe `call x_f ...` could be an expression-former instead of having an instruction of its own (because duplicating `const` is not very nice).

Another thing on the first pass is that I'm not convinced by the choice you made for nesting "segments" under "functions". Given your point on Monday that you want to play with an osr reconstructing several function frames, I would expect the reverse, that each segment has its own functions (possibly in different numbers).

**Comment by o-** [comment]
I did not make a pull request because I thought this is too far out to be mergable soon. But if you'd prefer I can certainly do it. Sorry for changing the patch below your feet.

As for the choice of including the "const a = " in the call instruction: yes I agree its ugly. I just wanted to avoid having two reduction relations for the whole machine state. Currently eval does not change the machine state, therefore we can have everything in just the one relation.

the last point is actually quite interesting. I guess it depends on the scope of your optimizations (whether you optimize one function or several functions in one go). But as soon as we inline you might be right. A downside of your approach is that we would have to copy all function we do not optimize if we create a new segment (because I think we should make "osr" to be the only segment-changing instruction).

**Comment by gasche** [comment]
Copying is fine: "yolo", as they say.

I'll think about your point on `eval`.

(Yes, you should do a PR because github does not give us the same tools to comment in-line etc. on just commits.)

**Comment by o-** [comment]
Ok, I'll create a PR tomorrow.

Btw. the most problematic part is imho the "close" expression. They way it is defined now it copies the environment. Which means that subsequent modifications do not affect the closure except for contents of the heap cells. This is a mess. But how to solve it? Copy everything? In R the closure gets a reference to the env (ie. every modification after the close is visible to the closure). But we probably want something cleaner.

**Comment by gasche** [comment]
I don't see the problem with "copying" the environment (given that environment structures are not mutated, we can always implement this with sharing if we want to; efficiency is not a concern here), as long as it is semantically correct. I believe that it is correct precisely thanks to the env/heap separation.

**Comment by gasche** [comment]
(I saw a version of the rule where you append the closure's environment to the current environment. It should be correct to only use the closure's environment (not having the current env. at all) during the evaluation of the function call, and keep only the current environment for the rest of the computation).

**Comment by o-** [comment]
well it might be a bit hard to reason, but maybe its alright. For example:

```
# Closure sees x:
cost x = 2
close fun
# Closure does not see x:
close fun
const x = 2
# Closure sees old x:
const x = 1
close fun
drop x
const x = 2
# closure sees new x
mut x = 1
close fun
x <- 2
```

But maybe you are right and those are exactly the features we want. Some more things I noticed:

```
# Some closure see x
loop:
  close x
  const x = 2
  goto loop
```

At least this is not possible thanks to the time we invested in the scopes.

And secondly:
We need free variables! otherwise the whole closure thing does not make sense at all :)

**Comment by gasche** [comment]
All your examples behave as they should, as far as I can tell. Eagerly waiting for your PR :-)

**Comment by o-** [comment]
okok #64
