### ISSUE TITLE
Broken optimizations due to scoping rules

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/sourir#98]
@o- [observed a problem with the constant folding optimization, but it also applies to other transformations.](https://github.com/reactorlabs/sourir/pull/97#pullrequestreview-35546726)

> Looking at your PR I came up with the following program which breaks your optimization pass for obvious reasons:
>
```
 const x = 1
 branch (0==1) b1 b2
b1:
 goto end
b2:
 drop x
 const x = 3
end:
 print x
```
>
>This is a nasty program and it's bad that we didn't see it coming. It's not just your optimization! For example
>
```
 const x = 1
 branch (0==1) b1 b2
b1:
 goto end
b2:
 drop x
 const x = 1
end:
```
> Is broken by the cleanup pass as it removes the unused 2nd declaration which renders the program ill-scoped.
>
> So I think we should probably fix it in the scope inference?

---

Part of the problem is that constant folding assumes the same static environment (mapping constant variables to values) can be used at all successors. But the problem seems to be more general than that, if we look at the second example. And I'm sure we could come up with more examples involving even more complicated control flow.

How do we want to fix this? We could make the optimizations smarter, or declare these programs as ill-scoped.

**Comment by o-** [comment]
Thanks for opening the issue. This is indeed something to discuss separately. I would like to rule out those examples by the scoping rules!
* For consts we could just require that every const has an unique name.
* Does it affect mut too? I am not sure...

**Comment by gasche** [comment]
I thought a bit about this yesterday -- thanks for the nice catch! The current scoping rules were designed to allow defining a variable in two branches of a conditional that would remain visible after the control-flow merge. I don't see an easy way to specify a scoping discipline that preserves this ability, yet rules out the example above. One solution would be for the scoping analysis to remember which variables where previously dropped and disallow re-declaring variables of the same name, but that seems very artificial and unpleasant to me.

We could give up and enforce that every variable has a unique binder, but then we would need some sort of phi-nodes (that is, osr-like environment remappings on gotos) to handle the case above.

Another solution I can see would be to define the optimizations to be robust to this example, by more systematically formulating them as dataflow analyses so that each bound occurrence is handled with the information of all incoming edges available.

**Comment by o-** [comment]
To be honest I am really unhappy with proposal 3. The scopes of variables are just biting us again and again.

I believe SSA is the way out. See #100 for a very lightweight ssa extension. The updated semantic should work correctly on correct SSA graphs. However so far I was not able to update the scoping judgment to verify the SSA construction. Some help would be appreciated.

Btw. i noticed that the formalism still lacks support for `drop` and `clear`. I think we should resolve this.

**Comment by mhyee** [comment]
I think we should rule out these examples. It seems bad that I can "modify" a const variable by dropping it and redeclaring it. It also seems wrong that I can have a consistent scope for both branches, by dropping and redeclaring a variable --- the `x` at the end of the branch actually refers to two different definitions of `x`!

SSA seems like a reasonable solution. I really don't like the other proposals (disallow redeclaring variables of the same name, making the examples legal and the optimizations more robust).

**Comment by mhyee** [comment]
To recap:

In our discussion, we realized that we were conflating const/mut variables with "cheap"/"expensive" storage. We decided to simplify this (proposal is #104, implementation in #107, #110, and finally in #121) and fixing up the optimizations (e.g. #119).

Have we confirmed that all the optimizations are working properly?

**Comment by gasche** [comment]
The testsuite passes. Is that not the same thing?

**Comment by mhyee** [comment]
The unit tests only run one optimization at a time. Moving some of the tests to `examples/` and running all optimizations might reveal more issues. I plan to do that (i.e. redo #114) soon.

**Comment by gasche** [comment]
It would be nice if we could have `tests/` for `.sou` files used for testing, and `examples/` for tested `.sou` file that are also supposed to be readable and interesting to a human.

**Comment by mhyee** [comment]
#135 runs all possible combination of optimizations on the examples.
